//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trust.Cgc.Computer.CncServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JobViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptField;
        
        private System.DateTime CreatedDateField;
        
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CncServiceReference.CncSoap")]
    public interface CncSoap {
        
        // CODEGEN: Generating message contract since element name identifier from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchJob", ReplyAction="*")]
        Trust.Cgc.Computer.CncServiceReference.FetchJobResponse FetchJob(Trust.Cgc.Computer.CncServiceReference.FetchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Trust.Cgc.Computer.CncServiceReference.FetchJobResponse> FetchJobAsync(Trust.Cgc.Computer.CncServiceReference.FetchJobRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchJob", Namespace="http://tempuri.org/", Order=0)]
        public Trust.Cgc.Computer.CncServiceReference.FetchJobRequestBody Body;
        
        public FetchJobRequest() {
        }
        
        public FetchJobRequest(Trust.Cgc.Computer.CncServiceReference.FetchJobRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchJobRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identifier;
        
        public FetchJobRequestBody() {
        }
        
        public FetchJobRequestBody(string identifier) {
            this.identifier = identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchJobResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trust.Cgc.Computer.CncServiceReference.FetchJobResponseBody Body;
        
        public FetchJobResponse() {
        }
        
        public FetchJobResponse(Trust.Cgc.Computer.CncServiceReference.FetchJobResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchJobResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trust.Cgc.Computer.CncServiceReference.JobViewModel FetchJobResult;
        
        public FetchJobResponseBody() {
        }
        
        public FetchJobResponseBody(Trust.Cgc.Computer.CncServiceReference.JobViewModel FetchJobResult) {
            this.FetchJobResult = FetchJobResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CncSoapChannel : Trust.Cgc.Computer.CncServiceReference.CncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CncSoapClient : System.ServiceModel.ClientBase<Trust.Cgc.Computer.CncServiceReference.CncSoap>, Trust.Cgc.Computer.CncServiceReference.CncSoap {
        
        public CncSoapClient() {
        }
        
        public CncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trust.Cgc.Computer.CncServiceReference.FetchJobResponse Trust.Cgc.Computer.CncServiceReference.CncSoap.FetchJob(Trust.Cgc.Computer.CncServiceReference.FetchJobRequest request) {
            return base.Channel.FetchJob(request);
        }
        
        public Trust.Cgc.Computer.CncServiceReference.JobViewModel FetchJob(string identifier) {
            Trust.Cgc.Computer.CncServiceReference.FetchJobRequest inValue = new Trust.Cgc.Computer.CncServiceReference.FetchJobRequest();
            inValue.Body = new Trust.Cgc.Computer.CncServiceReference.FetchJobRequestBody();
            inValue.Body.identifier = identifier;
            Trust.Cgc.Computer.CncServiceReference.FetchJobResponse retVal = ((Trust.Cgc.Computer.CncServiceReference.CncSoap)(this)).FetchJob(inValue);
            return retVal.Body.FetchJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trust.Cgc.Computer.CncServiceReference.FetchJobResponse> Trust.Cgc.Computer.CncServiceReference.CncSoap.FetchJobAsync(Trust.Cgc.Computer.CncServiceReference.FetchJobRequest request) {
            return base.Channel.FetchJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trust.Cgc.Computer.CncServiceReference.FetchJobResponse> FetchJobAsync(string identifier) {
            Trust.Cgc.Computer.CncServiceReference.FetchJobRequest inValue = new Trust.Cgc.Computer.CncServiceReference.FetchJobRequest();
            inValue.Body = new Trust.Cgc.Computer.CncServiceReference.FetchJobRequestBody();
            inValue.Body.identifier = identifier;
            return ((Trust.Cgc.Computer.CncServiceReference.CncSoap)(this)).FetchJobAsync(inValue);
        }
    }
}
